function Hd = FIR_window_HIGH_20
%FIR_WINDOW_HIGH_20 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 21-Nov-2016 01:57:55

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N    = 2;          % Order
Fc   = 20;         % Cutoff Frequency
flag = 'noscale';  % Sampling Flag
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag, 'h');
Hd = dfilt.dffir(b);
tf(Hd)
% [EOF]
