function Hd = IIR_BUTTER_LOW_70
%IIR_BUTTER_LOW_70 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 21-Nov-2016 00:18:18

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N  = 2;   % Order
Fc = 70;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
[B,A]=tf(Hd)

% [EOF]
